# CircleCI workflow config file
version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  fix-vulnerabilities:
    executor: node/default
    docker:
      - image: cimg/node:20.11.0-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Vulnerability Scan
          command: npm audit --json
      - run:
          name: Fix Vulnerabilities
          command: npm audit fix --force --json
          
  build-app:
    executor: node/default
    docker:
      - image: cimg/node:20.11.0-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build app
          command: npm install
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - .

  # deploy: # this can be any name you choose
  #   executor: heroku/default
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - heroku/deploy-via-git:
  #         force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  check-fix-build-app:
    jobs:
      - fix-vulnerabilities
      - build-app:
          requires:
            - fix-vulnerabilities
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: main # only deploy when on main
